### ISSUE TITLE
Typo in "14 HTML Fundamentals" video, 3:50

### ISSUE THREAD

**Issue by zachnewburgh** [learn-co-curriculum/html-fundamentals#2]
"[W]ere" should be "we're" in the final sentence of the slide at 3:50.
![screen shot 2016-01-18 at 11 38 22 am](https://cloud.githubusercontent.com/assets/9732085/12396916/04a60bd6-bdd8-11e5-8a9f-821469291e3e.png)

**Comment by AnnJohn** [comment]
thanks @zachnewburgh! we've noted this typo and will revisit it when we update our videos. Thanks again.
