### ISSUE TITLE
Spelling error in video

### ISSUE THREAD

**Issue by mjhough** [learn-co-curriculum/html-fundamentals#4]
At 3:45 in the video the final sentence of the text on screen says 'In this case were specifying HTML5'. It should read 'In this case we are specifying HTML5'.

**Comment by maxwellbenton** [comment]
Hi there @mjhough ,

Thank you for providing feedback on this repo.  Unfortunately, the captions provided in these videos are auto-generated by YouTube based on voice recognition, so they may not reflect correct grammar or spelling.

For now, I am going to close this issue, but we are in the process of reviewing and updating these labs, and will look into what can be done to improve clarity in these situations. 

As always, thanks for contributing! 💙
