### ISSUE TITLE
Incorrent Pronunciation of 'Attribute'

### ISSUE THREAD

**Issue by eroocodes** [learn-co-curriculum/html-fundamentals#5]
The speaker in this video pronounces the word 'attribute' as at-RI-bute throughout the duration of the video, rather than its proper pronunciation, AT-ri-bute. The video should be remade with proper pronunciation. Ex. at time marks 7:04, 7:37, 7:49, 7:54.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are currently in the process of rewriting and recording this section of lessons.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
